services:
  e2e:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    command: pnpm run test --watchAll
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo_sleepr
  reservations:
    build:
      context: ../
      dockerfile: ./apps/reservations/Dockerfile
      target: production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    build:
      context: ../
      dockerfile: ./apps/auth/Dockerfile
      target: production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    build:
      context: ../
      dockerfile: ./apps/payments/Dockerfile
      target: production
    env_file:
      - ../apps/payments/.env
  notifications:
    build:
      context: ../
      dockerfile: ./apps/notifications/Dockerfile
      target: production
    env_file:
      - ../apps/notifications/.env
  mongo_sleepr:
    image: mongo
